### ISSUE TITLE
Motion Guided Segmentation tool no longer available. 

### ISSUE THREAD

**Issue by iverzh** [denseanalysis/denseanalysis#25]
Hello DENSEanalysis crew!

I am a researcher at UCLA, running your DENSEanalysis package on Mac OS 10.11.3. I am using MatLab 2015b. When segmenting DENSE data, under the DENSE tab, it is no longer possible to use the Motion Guided Segmentation tool. It no longer appears under the list of options in the right-click menu. Is this due to the fact that I am using 2015b, or has the tool moved to a new location?

The tool worked great on the 2014 version of Matlab. 

Thank you very much for the help!

Ilya Verzhbinsky

**Comment by suever** [comment]
@ilyaver yes, the Motion Guided Segmentation tool has been removed from the core software due to the fact that it relies upon patented methodologies. Development of the plugin framework is currently underway and we will have an officlally-supported plugin for performing motion guided segmentation.

You can follow Issue #14 for updates on that.

I should have some major updates on that front this week.

**Comment by suever** [comment]
I'm going to go ahead and close this issue because the motion-guided segmentation plugin is complete and is available upon request until we come up with a better distribution mechanism.
